### ISSUE TITLE
I have a question about the paper!

### ISSUE THREAD

**Issue by simonZlz** [ihollywhy/SPAGAN#1]
Thanks for reading.
GAT stacks layer for larger receptive field. But SPAGAN obviously does not need to do that.
But why does the SPAGAN still stack layers. I would appreciate it if someone could reply to me.

**Comment by ihollywhy** [comment]
You can compare such setup with the conventional CNN, where one can increase the receptive field by using a larger size of the kernel but still stacks multiple layers. Stacking layers not only increases the receptive field but also brings more non-linear to the network and increases the representation capacity of it.
