### ISSUE TITLE
Question about the size of receptive field of SPAGAN

### ISSUE THREAD

**Issue by BenchengY** [ihollywhy/SPAGAN#2]
As I understand, if the SPAGAN has two layers and the max value of c is  three for the first layer and two for the last layer,  the size of receptive field of this SPAGAN is 5=3+2.
While, according to your paper Section 5.3,  3-layer GAT has the same size of  receptive field with SPAGAN. It seems the size of receptive field of SPAGAN is 3.

So, how to calculate the size of receptive field? why it is 3 rather than 5?

**Comment by ihollywhy** [comment]
The length of a path is measured by the number of nodes, including the root node itself. So, a path with a length of three will increase the size of the receptive field by two rather than three.

**Comment by BenchengY** [comment]
Thanks.
